### ISSUE TITLE
In display menu we need to work around user crashing with wrong input.

### ISSUE THREAD

**Issue by Liam-McLaughlin-GH** [liamandaidan/CPRG251_A1_Group_2#11]
We may need to add to the switch. Consult Mike for more info! @liamandaidan @IronsideZero @Mikepcann @rawbz

**Comment by rawbz** [comment]
added 'default' to the switch in displayMenu(), requests user to reenter if it doesn't match the menu options.

**Comment by Liam-McLaughlin-GH** [comment]
Awesome!

**Comment by Liam-McLaughlin-GH** [comment]
How do we fell about crashing with user input? Are finished now? @Mikepcann
