### ISSUE TITLE
Random book list crash

### ISSUE THREAD

**Issue by Mikepcann** [liamandaidan/CPRG251_A1_Group_2#19]
Could you tackle the issue here. Make sure it can accept any input type without crashing, and if not a number, ask the user to write a number.
for the trillion book list crash, maybe you could set the max length to the length of the book list?

**Comment by Liam-McLaughlin-GH** [comment]
You betchya. I got that covered 💯

**Comment by Liam-McLaughlin-GH** [comment]
`numOfRandomBooks = Integer.parseInt(in.nextLine());
				if (numOfRandomBooks <= 50 && numOfRandomBooks >= 0) {
					produceRandomBookList(numOfRandomBooks);
				} else {
					System.out.println("Wrong user Input. Please use an appropriate number from 1-50.");
				}`
This should be the fix! I have it in liam branch. I will try and create a pull request. And see if it can link to this issue
